(DEFINE (reverse-general L)
  (COND
    ((NULL? L) L)
    ((LIST? (CAR L))
        (reverse-general (CAR L)))
    (CONS (CAR L) (CDR (CDR L)))
    (ELSE reverse-general (CDR L))
  )
 )
(DEFINE (sum-up-numbers-simple L)
        (COND
         ((NULL? L) L)
         ((LIST? (CAR L)) L)
         ((NUMBER? (CAR L)) (DISPLAY "num "))
         (ELSE (DISPLAY "not "))
         )
        ((NOT (NULL? L)
              (sum-up-numbers-simple (CDR L))))
        )